### PR TITLE
V2.0.0

### PR DESCRIPTION
**Pull request by matthewtiscareno**
## Summary

Add units to plate_scale (backwards-incompatible, thus triggering a major version)

## Test Data and/or Report

Enter info here

## Related Issues

Enter related issues here

### CODE REVIEW

**Review by mace-space — APPROVED** [review]
Looks good.

**Comment by matthewtiscareno** [comment]
Thanks, but I think we decided to actually close this pull request and create a new one that goes to version 1.1 instead of 2.0.  Even though the addition of units to plate_scale is technically backwards-incompatible, nobody is yet using this LDD for any purpose except Dave, so we can say that the LDD is still "in development" and there's no need to drive up the version numbers at this point. 

Please confirm whether this seems good, and then I'll close this PR, delete this branch, and create a new branch and PR with the version incremented to 1.1 and otherwise identical to this.

**Comment by mace-space** [comment]
Oh I see. Yes, that seems good.

**Comment by matthewtiscareno** [comment]
I've now created https://github.com/pds-data-dictionaries/ldd-hst/pull/11, so closing this PR and deleting the branch.

**Pull request closed without merging**
